-- LISTADO DE REGISTROS POR MEDIO DE COMURSAL
CREATE PROCEDURE SP_L_COMPANIA_01
AS
BEGIN
	SELECT * FROM TM_COMPANIA
	WHERE
    -- SOLO CON ESTADO ACTIVO
	EST=1
END

-- OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_COMPANIA_02
@COM_ID INT
AS
BEGIN
	SELECT * FROM TM_COMPANIA
	WHERE
	COM_ID = @COM_ID
END

-- ELIMINAR REGISTRO POR ID
CREATE PROCEDURE SP_D_COMPANIA_01
@COM_ID INT
AS
BEGIN
	UPDATE TM_COMPANIA
	SET
		EST= 0
	WHERE
		COM_ID = @COM_ID
END

-- INSERTAR NUEVOS REGISTROS
CREATE PROCEDURE SP_I_COMPANIA_01
@COM_NOM VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_COMPANIA
	(COM_NOM,FECH_CREA,EST)
	VALUES
	(@COM_NOM,GETDATE(),1)
END

-- ACTUALIZAR REGISTROS
CREATE PROCEDURE SP_U_COMPANIA_01
@COM_ID INT,
@COM_NOM VARCHAR(150)
AS
BEGIN
	UPDATE TM_COMPANIA
	SET
		COM_NOM = @COM_NOM
	WHERE
		COM_ID = @COM_ID
END