-- LISTADO DE REGISTROS POR MEDIO DE SUCURSAL
CREATE PROCEDURE SP_L_EMPRESA_01
@COM_ID INT
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE
	COM_ID = @COM_ID
	AND EST=1
END

-- OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_EMPRESA_02
@EMP_ID INT
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE
	EMP_ID = @EMP_ID
END

-- ELIMINAR REGISTRO POR ID
CREATE PROCEDURE SP_D_EMPRESA_01
@EMP_ID INT
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		EST= 0
	WHERE
		EMP_ID = @EMP_ID
END

-- INSERTAR NUEVOS REGISTROS
CREATE PROCEDURE SP_I_EMPRESA_01
@COM_ID INT,
@EMP_NOM VARCHAR(150),
@EMP_RZ VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_EMPRESA
	(COM_ID,EMP_NOM,EMP_RZ,FECH_CREA,EST)
	VALUES
	(@COM_ID,@EMP_NOM,@EMP_RZ,GETDATE(),1)
END

-- ACTUALIZAR REGISTROS
CREATE PROCEDURE SP_U_EMPRESA_01
@EMP_ID INT,
@COM_ID INT,
@EMP_NOM VARCHAR(150),
@EMP_RZ VARCHAR(150)
AS
BEGIN
	UPDATE TM_EMPRESA
	SET 
		COM_ID = @COM_ID,
		EMP_NOM = @EMP_NOM,
		EMP_RZ =  @EMP_RZ
	WHERE
		EMP_ID = @EMP_ID
END