-- LISTADO DE REGISTROS POR MEDIO DE SUCURSAL
CREATE PROCEDURE SP_L_PRODUCTO_01
@SUC_ID INT
AS
BEGIN
	SELECT * FROM TM_PRODUCTO
	WHERE 
	SUC_ID = @SUC_ID
	-- SOLO CON ESTADO ACTIVO
	AND EST=1
END

-- OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_PRODUCTO_02
@PROD_ID INT
AS
BEGIN
	SELECT * FROM TM_PRODUCTO
	WHERE 
	PROD_ID = @PROD_ID
END

-- ELIMINAR REGISTRO POR ID
CREATE PROCEDURE SP_D_PRODUCTO_01
@PROD_ID INT
AS
BEGIN
	UPDATE TM_PRODUCTO
	SET
		EST= 0	
	WHERE	
		PROD_ID = @PROD_ID
END

-- INSERTAR NUEVOS REGISTROS
CREATE PROCEDURE SP_I_PRODUCTO_01
@SUC_ID INT,
@CAT_ID INT,
@UND_ID INT,
@MON_ID INT,
@PROD_NOM VARCHAR(150),
@PROD_DESCRIP VARCHAR(200),
@PROD_PRECIO NUMERIC(18,2),
@PROD_STOCK INT,
@PROD_FECHAVEN DATE,
@PROD_IMG VARCHAR(MAX)
AS
BEGIN
	INSERT INTO TM_PRODUCTO
	(SUC_ID,CAT_ID,UND_ID,MON_ID,PROD_NOM,PROD_DESCRIP,PROD_PRECIO,PROD_STOCK,PROD_FECHAVEN,PROD_IMG,FECH_CREA,EST)
	VALUES
	(@SUC_ID,@CAT_ID,@UND_ID,@MON_ID,@PROD_NOM,@PROD_DESCRIP,@PROD_PRECIO,@PROD_STOCK,@PROD_FECHAVEN,@PROD_IMG,GETDATE(),1)
END

-- ACTUALIZAR REGISTROS
CREATE PROCEDURE SP_U_PRODUCTO_01
@PROD_ID INT,
@SUC_ID INT,
@CAT_ID INT,
@UND_ID INT,
@MON_ID INT,
@PROD_NOM VARCHAR(150),
@PROD_DESCRIP VARCHAR(200),
@PROD_PRECIO NUMERIC(18,2),
@PROD_STOCK INT,
@PROD_FECHAVEN DATE,
@PROD_IMG VARCHAR(MAX)
AS
BEGIN
	UPDATE TM_PRODUCTO
	SET 
		SUC_ID = @SUC_ID,
		CAT_ID = @CAT_ID,
		UND_ID = @UND_ID,
		MON_ID = @MON_ID,
		PROD_NOM = @PROD_NOM,
		PROD_DESCRIP = @PROD_DESCRIP,
		PROD_PRECIO = @PROD_PRECIO,
		PROD_STOCK = @PROD_STOCK,
		PROD_FECHAVEN = @PROD_FECHAVEN,
		PROD_IMG = @PROD_IMG
	WHERE
		PROD_ID = @PROD_ID
END