-- LISTADO DE REGISTROS POR MEDIO DE SUCURSAL
CREATE PROCEDURE SP_L_TRABAJADOR_01
@EMP_ID INT
AS
BEGIN
	SELECT * FROM TM_TRABAJADOR
	WHERE 
	EMP_ID = @EMP_ID
	-- SOLO CON ESTADO ACTIVO
	AND EST=1
END

-- OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_TRABAJADOR_02
@TRA_ID INT
AS
BEGIN
	SELECT * FROM TM_TRABAJADOR
	WHERE 
	TRA_ID = @TRA_ID
END

-- ELIMINAR REGISTRO POR ID
CREATE PROCEDURE SP_D_TRABAJADOR_01
@TRA_ID INT
AS
BEGIN
	UPDATE TM_TRABAJADOR
	SET
		EST= 0	
	WHERE	
		TRA_ID = @TRA_ID
END

-- INSERTAR NUEVOS REGISTROS
CREATE PROCEDURE SP_I_TRABAJADOR_01
@EMP_ID INT,
@TRA_NOM VARCHAR(150),
@TRA_CORREO VARCHAR(150),
@TRA_PUESTO VARCHAR(150),
@TRA_AREA VARCHAR(150),
@TRA_TELF VARCHAR(50),
@TRA_DNI VARCHAR(50),
@TRA_DIRECC VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_TRABAJADOR
	(EMP_ID,TRA_NOM,TRA_CORREO,TRA_PUESTO,TRA_AREA,TRA_TELF,TRA_DNI,TRA_DIRECC,FECH_CREA,EST)
	VALUES
	(@EMP_ID,@TRA_NOM,@TRA_CORREO,@TRA_PUESTO,@TRA_AREA,@TRA_TELF,@TRA_DNI,@TRA_DIRECC,GETDATE(),1)
END

-- ACTUALIZAR REGISTROS
CREATE PROCEDURE SP_U_TRABAJADOR_01
@EMP_ID INT,
@TRA_ID INT,
@TRA_NOM VARCHAR(150),
@TRA_CORREO VARCHAR(150),
@TRA_PUESTO VARCHAR(150),
@TRA_AREA VARCHAR(150),
@TRA_TELF VARCHAR(50),
@TRA_DNI VARCHAR(50),
@TRA_DIRECC VARCHAR(150)
AS
BEGIN
	UPDATE TM_TRABAJADOR
	SET 
		EMP_ID = @EMP_ID,
		TRA_NOM = @TRA_NOM,
		TRA_CORREO = @TRA_CORREO,
		TRA_PUESTO = @TRA_PUESTO,
		TRA_AREA = @TRA_AREA,
		TRA_TELF = @TRA_TELF,
		TRA_DNI = @TRA_DNI,
		TRA_DIRECC = @TRA_DIRECC
	WHERE
		TRA_ID = @TRA_ID
END