-- LISTADO DE REGISTROS POR MEDIO DE SUCURSAL
CREATE PROCEDURE SP_L_USUARIO_01
@SUC_ID INT
AS
BEGIN
	SELECT * FROM TM_USUARIO
	WHERE 
	SUC_ID = @SUC_ID
	-- SOLO CON ESTADO ACTIVO
	AND EST=1
END

-- OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_USUARIO_02
@USU_ID INT
AS
BEGIN
	SELECT * FROM TM_USUARIO
	WHERE 
	USU_ID = @USU_ID
END

-- ELIMINAR REGISTRO POR ID
CREATE PROCEDURE SP_D_USUARIO_01
@USU_ID INT
AS
BEGIN
	UPDATE TM_USUARIO
	SET
		EST= 0	
	WHERE	
		USU_ID = @USU_ID
END

-- INSERTAR NUEVOS REGISTROS
CREATE PROCEDURE SP_I_USUARIO_01
@SUC_ID INT,
@ROL_ID INT,
@USU_CORREO VARCHAR(150),
@USU_PASS VARCHAR(100),
@USU_NOM VARCHAR(150),
@USU_APE VARCHAR(150),
@USU_PUESTO VARCHAR(150),
@USU_AREA VARCHAR(150),
@USU_DNI VARCHAR(50),
@USU_TELF VARCHAR(50)
AS
BEGIN
	INSERT INTO TM_USUARIO
	(SUC_ID,ROL_ID,USU_CORREO,USU_PASS,USU_NOM,USU_APE,USU_PUESTO,USU_AREA,USU_DNI,USU_TELF,FECH_CREA,EST)
	VALUES
	(@SUC_ID,@ROL_ID,@USU_CORREO,@USU_PASS,@USU_NOM,@USU_APE,@USU_PUESTO,@USU_AREA,@USU_DNI,@USU_TELF,GETDATE(),1)
END

-- ACTUALIZAR REGISTROS
CREATE PROCEDURE SP_U_USUARIO_01
@USU_ID INT,
@SUC_ID INT,
@ROL_ID INT,
@USU_CORREO VARCHAR(150),
@USU_PASS VARCHAR(100),
@USU_NOM VARCHAR(150),
@USU_APE VARCHAR(150),
@USU_PUESTO VARCHAR(150),
@USU_AREA VARCHAR(150),
@USU_DNI VARCHAR(50),
@USU_TELF VARCHAR(50)
AS
BEGIN
	UPDATE TM_USUARIO
	SET 
		SUC_ID = @SUC_ID,
		ROL_ID = @ROL_ID,
		USU_CORREO = @USU_CORREO,
		USU_PASS = @USU_PASS,
		USU_NOM = @USU_NOM,
		USU_APE = @USU_APE,
		USU_PUESTO = @USU_PUESTO,
		USU_AREA = @USU_AREA,
		USU_DNI = @USU_DNI,
		USU_TELF = @USU_TELF
	WHERE
		USU_ID = @USU_ID
END

-- ACCESO DE USUARIO
CREATE PROCEDURE SP_L_USUARIO_03
@USU_CORREO VARCHAR(100),
@USU_PASS VARCHAR(100)
AS
BEGIN
	SELECT * FROM TM_USUARIO
	WHERE 
	-- SI EL CORREO Y LA CONTRASENA SON LOS CORRECTOS REGRESA UNA RESPUESTA
	USU_CORREO = @USU_CORREO
	AND USU_PASS = @USU_PASS
	-- SOLO CON ESTADO ACTIVO
	AND EST=1
END

-- CAMBIO DE CONTRASEÑA
CREATE PROCEDURE SP_U_USUARIO_02
@USU_ID INT,
@USU_PASS VARCHAR(100)
AS
BEGIN
	UPDATE TM_USARIO
	SET
		USU_PASS = @USU_PASS
		WHERE
		@USU_ID = USU_ID
END
