USE fiseinventario

-- LISTADO DE REGISTROS POR MEDIO DE SUCURSAL  
ALTER PROCEDURE SP_L_CATEGORIA_01  
@SUC_ID INT  
AS  
BEGIN  
 SELECT 
	 CAT_ID,
	 SUC_ID,
	 CAT_NOM,
	 CONVERT(VARCHAR,FECH_CREA,103) AS FECH_CREA,
	 EST
 FROM 
	TM_CATEGORIA  
 WHERE   
	 SUC_ID = @SUC_ID  
	 -- SOLO CON ESTADO ACTIVO  
	 AND EST=1  
END

SELECT * FROM TM_CATEGORIA

-- PONER EN ESTADO DE ALTA
update TM_CATEGORIA
set		
	EST=1